/*
    Copyright (c) 2026 - Yann BOYER
*/
#ifndef CONSTS_H
#define CONSTS_H

#define CHIP8_SCREEN_WIDTH 64
#define CHIP8_SCREEN_HEIGHT 32
#define PIXEL_SCALE_FACTOR 10
#define WINDOW_WIDTH (CHIP8_SCREEN_WIDTH * PIXEL_SCALE_FACTOR)
#define WINDOW_HEIGHT (CHIP8_SCREEN_HEIGHT * PIXEL_SCALE_FACTOR)
#define CPU_CLOCK_DELAY 1 // 1ms.
#define TIMER_CLOCK_DIVISION 9
// CPU's PC starts at 0x200(512).
#define CPU_INTERNAL_PROGRAM_COUNTER_START 0x200

#endif
